# nixpacks.toml

[phases.setup]
nixPkgs = [
  # Paquete principal de PHP que provee php-fpm
  "pkgs.php82",

  # Dependencias del entorno por defecto de Railway
  "pkgs.nodejs_18",
  "pkgs.nginx",
  
  # Dependencias de la aplicación
  "pkgs.php82Packages.composer", 
  "pkgs.php82Extensions.pdo_mysql",
  "pkgs.php82Extensions.zip",
  "pkgs.php82Extensions.xml",
  "pkgs.php82Extensions.gd",
  "pkgs.php82Extensions.mbstring",
  "pkgs.php82Extensions.curl",
  "pkgs.php82Extensions.intl"
] 