# nixpacks.toml

[phases.setup]
nixPkgs = [
  "pkgs.apacheHttpd", 
  "pkgs.php82Packages.composer", 
  "pkgs.php82Extensions.pdo_mysql",
  "pkgs.php82Extensions.zip",
  "pkgs.php82Extensions.xml",
  "pkgs.php82Extensions.gd"
]

[start]
cmd = "apache2-foreground" 