# nixpacks.toml

[providers]
php = "7.4"

[phases.setup]
nixPkgs = [
    "pkgs.php74",
    "pkgs.php74Packages.composer",
    "pkgs.php74Extensions.pdo_mysql",
    "pkgs.php74Extensions.zip",
    "pkgs.php74Extensions.xml",
    "pkgs.php74Extensions.gd",
    "pkgs.php74Extensions.mbstring",
    "pkgs.php74Extensions.curl",
    "pkgs.php74Extensions.intl"
]

# Dejamos que Nixpacks maneje el build y el start por defecto.
# Solo nos aseguramos de que el directorio de logs exista.
[phases.build]
cmds = [
    "composer install --no-dev --ignore-platform-reqs",
    "mkdir -p FUNCTIONAL/logs",
    "chmod -R 777 FUNCTIONAL/logs"
]